name: rebuild website 
on:
  push:
    branches: 
      - master

jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:

      # Checks-out your repository under $GITHUB_WORKSPACE, so this workflow job can access it
      - name: Checkout master branch
        uses: actions/checkout@v2

      # set up python environment
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.6.15

      # installs the dependencies mkdocs needs to build our website. 
      # dependencies are listed in 'requirements.txt' - markdown-include, mkdocs-material etc
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      # builds our website and deploys to github-pages. 
      - name: Generate + deploy website
        run: mkdocs gh-deploy --force
        
